package org.exceptions;

public class Exceptions 
{

	public static void main(String[] args)
	{
//		//Arithmetic
//		System.out.println(1);
//		System.out.println(2);
//		try
//		{
//		System.out.println(3/0);
//		}
//		catch (ArithmeticException a)
//		{
//			System.out.println("Don't try to divide by 0..");
//		}
//		finally
//		{
//			System.out.println("Exception Handled successfully");
//		}
//		System.out.println(4);
	////******************************
//       //String 
//		String name="eswar";
//		char fl= name.charAt(5);
//		System.out.println(fl);
    ////******************************
		//array
		int a[]=new int[6];
		a[0]=10; 
		a[3]=20; 
		a[5]=25; 
		a[1]=15; 
		
		System.out.println(a[6]);
   ////*****************************
		
		

	}

}
